ACTION_IF (VARIABLE_IS_SET ~zs_itempack_110~) BEGIN
  FAIL ~Script already included: zs_itempack_110~
END ELSE BEGIN
  OUTER_SET ~zs_itempack_110~ = 1
END

ACTION_IF GAME_IS ~bgee bg2ee eet~ OR GAME_IS "iwdee" AND FILE_EXISTS_IN_GAME ~l#dendj.cre~ BEGIN

  DEFINE_PATCH_MACRO add BEGIN ADD_CRE_ITEM ~zsipckaa~ #0 #0 #0 ~unstealable~ ~cloak~ END
  COPY ~%MOD_FOLDER%/items/01_forbidden_game/deathstalker_mantle~ ~override~
  COPY_EXISTING ~zsipckaa.itm~ ~override~
    SAY NAME2 @5040
    SAY IDENTIFIED_DESC @5041
    WRITE_LONG 0x34 zst_price_deathstalker_mantle

  ACTION_IF GAME_IS ~bgee eet~ BEGIN
    COPY_EXISTING ~vayya.cre~ ~override~
      LPM add
  END

  ACTION_IF GAME_IS ~bg2ee eet~ BEGIN
    COPY_EXISTING ~idemon02.cre~ ~override~
      LPM add
  END

  ACTION_IF GAME_IS "iwdee" BEGIN
    COPY_EXISTING ~l#dendj.cre~ ~override~
      LPM add
  END

END ELSE BEGIN WARN "[IWDEE Warning]: Dendjelion from Lava is not installed. Skipping..." END


