COPY ~%MOD_FOLDER%/items/01_bg3/ritual_dagger~ ~override~
COPY_EXISTING ~zsipdgri.itm~ ~override~
  SAY NAME2 @5012
  SAY IDENTIFIED_DESC @5013
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF(@5014) END
  WRITE_LONG 0x34 zst_price_ritual_dagger

ACTION_IF GAME_IS "bgee eet" BEGIN

  COPY_EXISTING ~bassil.cre~ ~override~
    ADD_CRE_ITEM ~zsipdgri~ #3 #0 #0 ~none~ ~inv~

END

ACTION_IF GAME_IS "bg2ee eet" BEGIN

  COPY_EXISTING ~duecla01.cre~ ~override~
    ADD_CRE_ITEM ~zsipdgri~ #3 #0 #0 ~none~ ~inv~

END
