COPY ~%MOD_FOLDER%/items/02_souls/stygian_fury~ ~override~
COPY_EXISTING ~zsipsf00.itm~ ~override~
  SAY NAME2 @6090
  SAY IDENTIFIED_DESC @6091
  WRITE_LONG 0x34 zst_price_stygian_fury

COPY_EXISTING ~zsipsf05.spl~ ~override~
              ~zsipsf12.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF(@6092) END

COPY_EXISTING ~obsdem01.cre~ ~override~
  ADD_CRE_ITEM ~zsipsf00~ #0 #0 #0 ~unstealable~ ~inv~

COPY_EXISTING ~zsipsf07.itm~ ~override~
  SAY NAME2 @6093
  SAY IDENTIFIED_DESC @6094
  WRITE_LONG 0x34 zst_price_stygian_fury_upgraded

COMPILE ~%MOD_FOLDER%/dlg/upgrades/zs_itempack_stygian_fury_cespy.d~
EXTEND_BOTTOM ~botsmith.bcs~ ~%MOD_FOLDER%/baf/upgrades/stygian_fury/botsmith.baf~
