ACTION_IF (VARIABLE_IS_SET ~zs_itempack_501~) BEGIN
  FAIL ~Script already included: zs_itempack_501~
END ELSE BEGIN
  OUTER_SET ~zs_itempack_501~ = 1
END

COPY ~%MOD_FOLDER%/items/05_tv/needle~ ~override~
COPY_EXISTING ~ZSIPNDL0.itm~ ~override~
    SAY NAME1 @80110
    SAY NAME2 @12000
    SAY UNIDENTIFIED_DESC @80111
    SAY IDENTIFIED_DESC @12001
BUT_ONLY


INCLUDE ~%MOD_FOLDER%/lib/zs_add_rapiers.tph~
