COPY ~%MOD_FOLDER%/items/01_bg3/cruel_sting~ ~override~
COPY_EXISTING ~zsipcst0.itm~ ~override~
  SAY NAME2 @5019
  SAY IDENTIFIED_DESC @5020
  WRITE_LONG 0x34 zst_price_cruel_sting_bgee

COPY_EXISTING ~zsipcst3.itm~ ~override~
  SAY NAME2 @5022
  SAY IDENTIFIED_DESC @5023
  WRITE_LONG 0x34 zst_price_cruel_sting_bg2ee

COPY_EXISTING ~zsipcst2.spl~ ~override~
  SAY NAME1 @5021

ACTION_IF GAME_IS "bgee eet" BEGIN

  COPY_EXISTING ~centeo.cre~ ~override~
    ADD_CRE_ITEM ~zsipcst0~ #2 #0 #0 ~none~ ~inv~

END

ACTION_IF GAME_IS "bg2ee eet" BEGIN

  COPY_EXISTING ~ar0804.are~ ~override~
    LPF ADD_AREA_ITEM INT_VAR container_to_add_to = 1 charges1=2 STR_VAR item_to_add = ~zsipcst3~ END

END
