COPY ~%MOD_FOLDER%/items/02_souls/icicle~ ~override~
COPY_EXISTING ~zsipici0.itm~ ~override~
  SAY NAME1 @80110
  SAY NAME2 @6070
  SAY UNIDENTIFIED_DESC @80111
  SAY IDENTIFIED_DESC @6071
  WRITE_LONG 0x34 zst_price_icicle

ACTION_IF GAME_IS "bg2ee eet" BEGIN

  COPY_EXISTING ~udmaster.cre~ ~override~
    ADD_CRE_ITEM ~zsipici0~ #0 #0 #0 ~unstealable~ ~inv~

END

INCLUDE ~%MOD_FOLDER%/libs/zs_add_rapiers.tph~
