COPY ~%MOD_FOLDER%/items/03_nwn/squire_defense~ ~override~
COPY_EXISTING ~zsipsqd0.itm~ ~override~
    SAY NAME2 @13070
    SAY IDENTIFIED_DESC @13071
    WRITE_LONG 0x34 zst_price_squire_defense

ACTION_IF GAME_IS ~bgee eet~ BEGIN

    COPY_EXISTING ~taerum.sto~ ~override~
        LPF ADD_STORE_ITEM_EX STR_VAR flags=~identified~ item_name = "zsipsqd0" position = "LAST" END

END

ACTION_IF GAME_IS ~bg2ee eet~ BEGIN

    COPY_EXISTING ~shop02.sto~ ~override~
        LPF ADD_STORE_ITEM_EX STR_VAR flags=~identified~ item_name = "zsipsqd0" position = "LAST" END

END
