COPY ~%MOD_FOLDER%/items/02_souls/spellguard~ ~override~
COPY_EXISTING ~zsipspg0.itm~ ~override~
  SAY NAME2 @6120
  SAY IDENTIFIED_DESC @6121

  PATCH_IF NOT GAME_IS "iwdee" BEGIN
    WRITE_LONG 0x34 zst_price_spellguard_bg
  END ELSE BEGIN
    WRITE_LONG 0x34 zst_price_spellguard_iwdee
  END

ACTION_IF GAME_IS "bgee eet" BEGIN

  COPY_EXISTING ~highhedg.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR item_name = "zsipspg0" position = "LAST" flags="identified" END

END

ACTION_IF GAME_IS "bg2ee eet" BEGIN

  COPY_EXISTING ~trmer02.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR item_name = "zsipspg0" position = "LAST" flags="identified" END

END

ACTION_IF GAME_IS "iwdee" BEGIN

  COPY_EXISTING ~eldathl.cre~ ~override~
    ADD_CRE_ITEM ~zsipspg0~ #0 #0 #0 ~none~ ~inv~

END