COPY ~%MOD_FOLDER%/items/01_forbidden_game/assassins_touch~ ~override~
COPY_EXISTING ~zsipass0.itm~ ~override~
  SAY NAME2 @5010
  SAY IDENTIFIED_DESC @5011
  WRITE_LONG 0x34 zst_price_assassins_touch_bgee_iwdee

COPY_EXISTING ~zsipass4.itm~ ~override~
  SAY NAME2 @50110
  SAY IDENTIFIED_DESC @50111
  WRITE_LONG 0x34 zst_price_assassins_touch_bg2ee

ACTION_IF GAME_IS "bgee eet" BEGIN

  COPY_EXISTING ~inn3351.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR flags=~identified~ item_name = "zsipass0" position = "LAST" END

END

ACTION_IF GAME_IS "bg2ee eet" BEGIN

  COPY_EXISTING ~bmthief.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR flags=~identified~ item_name = "zsipass4" position = "LAST" END

END

ACTION_IF GAME_IS "iwdee" BEGIN

  COPY_EXISTING ~bmthief.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR flags=~identified~ item_name = "zsipass4" position = "LAST" END

END