COPY ~%MOD_FOLDER%/items/01_bg3/ring_shadows~ ~override~
COPY_EXISTING ~zsirgsd0.itm~ ~override~
  SAY NAME2 @5060
  SAY IDENTIFIED_DESC @5061
  WRITE_LONG 0x34 zst_price_ring_shadows

OUTER_SET is_eet = GAME_IS "eet"

ACTION_IF GAME_IS "bg2ee" OR is_eet BEGIN

    COPY_EXISTING ~bmthief.sto~ ~override~
        LPF ADD_STORE_ITEM_EX STR_VAR item_name="zsirgsd0" position="LAST" flags=~identified~ END

END

ACTION_IF GAME_IS "bgee" OR is_eet BEGIN

    COPY_EXISTING ~diana.cre~ ~override~
        ADD_CRE_ITEM ~zsirgsd0~ #0 #0 #0 ~unstealable~ ~boots inv~

END

ACTION_IF GAME_IS "iwdee" BEGIN

    COPY_EXISTING ~erevdead.cre~ ~override~
        ADD_CRE_ITEM ~zsirgsd0~ #0 #0 #0 ~none~ ~boots inv~

END