ACTION_IF (VARIABLE_IS_SET ~zs_itempack_304~) BEGIN
  FAIL ~Script already included: zs_itempack_304~
END ELSE BEGIN
  OUTER_SET ~zs_itempack_304~ = 1
END

COPY ~%MOD_FOLDER%/items/03_nwn/kukri_eclipse~ ~override~
COPY_EXISTING ~ZSIPKRE0.itm~ ~override~
    SAY NAME2 @8008
    SAY IDENTIFIED_DESC @8009
BUT_ONLY

COPY_EXISTING ~DRAGBLAC.CRE~ ~override~ // NIZINIZINIZINIZINIZI
    ADD_CRE_ITEM ~ZSIPKRE0.itm~ #1 #0 #0 ~unstealable~ ~inv~
BUT_ONLY IF_EXISTS

// todo: add the upgrade for the kukri
