COPY ~%MOD_FOLDER%/items/03_nwn/arrows_vampire~ ~override~
COPY_EXISTING ~zsipavp0.itm~ ~override~
    SAY NAME2 @15100
    SAY IDENTIFIED_DESC @15101
    WRITE_LONG 0x34 zst_price_arrows_vampire

ACTION_IF GAME_IS ~bgee eet~ BEGIN

  COPY_EXISTING ~bdbelega.sto~ ~override~ // belegarm's store (quartermaster sod)
                ~bdsorcsc.sto~ ~override~ // sorcerous sundries (sod)
                ~sto0703.sto~  ~override~ // sorcerous sundries
                ~erdane.sto~   ~override~ // erdane
                ~highhedg.sto~ ~override~ // high hedge
                ~ulgoth.sto~   ~override~ // ulgoth
                ~stoblack.sto~ ~override~ // black lily
                ~stosilen.sto~ ~override~ // silence
                ~taerum.sto~   ~override~ // thunderhammer's smithy
                ~bdwaizah.sto~ ~override~ // thieves guild sod
    LPF ADD_STORE_ITEM_EX INT_VAR charge1=10 stack=40 STR_VAR item_name="zsipavp0" position="LAST" flags=~identified~ END
  BUT_ONLY IF_EXISTS

END

ACTION_IF GAME_IS ~bg2ee eet~ BEGIN

  COPY_EXISTING ~amsmug01.sto~ ~override~ // smugglers 1
                ~amsmug02.sto~ ~override~ // smugglers 2
                ~arled.sto~    ~override~ // arled
                ~bernard.sto~  ~override~ // bernard 1
                ~bernard2.sto~ ~override~ // bernard 2
                ~bernard3.sto~ ~override~ // bernard 3
                ~bernard4.sto~ ~override~ // bernard 4
                ~bernard5.sto~ ~override~ // bernard 4
                ~bernard6.sto~ ~override~ // bernard 4
                ~gorch.sto~    ~override~ // gorch
                ~hendak.sto~   ~override~ // hendak
                ~lehtinan.sto~ ~override~ // lehtinan
                ~ribald.sto~   ~override~ // ribald
                ~shthstor.sto~ ~override~ // ratell
                ~trmer03.sto~  ~override~ // fletcher
                ~sarbar01.sto~ ~override~ // saradush inn
    LPF ADD_STORE_ITEM_EX INT_VAR charge1=20 stack=10 STR_VAR item_name="zsipavp0" position="LAST" flags=~identified~ END

  COPY_EXISTING ~bmthief.sto~ ~override~ // shadow thief fence
                ~ribald2.sto~ ~override~ // ribald
                ~hgkar01.sto~ ~override~ // karthis
    LPF ADD_STORE_ITEM_EX INT_VAR charge1=20 stack=15 STR_VAR item_name="zsipavp0" position="LAST" flags=~identified~ END

END

ACTION_IF GAME_IS ~iwdee~ BEGIN

  COPY_EXISTING_REGEXP ~^.+\.sto~ ~override~
  
      READ_LONG 0x38 items_sale
      PATCH_IF items_sale > 0 BEGIN
        READ_LONG 0x34 items_sale_offset
        SET last_offset = items_sale_offset + ( (items_sale - 1 ) * 28)

        FOR (i = items_sale_offset; i < last_offset; i += 28) BEGIN
            READ_ASCII i resource (8)
            SET matched = 0
            INNER_PATCH_FILE ~%resource%.itm~ BEGIN
                READ_SHORT 0x1c category

                PATCH_IF category = 5 BEGIN

                    SET stacks = RANDOM(1 10)
                    SET size_stack = RANDOM(1 8)

                    LPF ADD_STORE_ITEM_EX INT_VAR charge1=(size_stack * 5) stack=stacks STR_VAR item_name="zsipavp0" position="LAST" flags=~identified~ END

                    SET matched = 1
                END
              
            END

            PATCH_IF matched = 1 BEGIN
              i = last_offset
            END

        END

      END

  BUT_ONLY

END
