COPY ~%MOD_FOLDER%/items/01_forbidden_game/spell_siphon~ ~override~
COPY_EXISTING ~zsipsps0.itm~ ~override~
  SAY NAME2 @5017
  SAY IDENTIFIED_DESC @5018
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF(@50180) END
  WRITE_LONG 0x34 zst_price_spell_siphon_bgee

COPY_EXISTING ~zsipsps2.itm~ ~override~
  SAY NAME2 @50182
  SAY IDENTIFIED_DESC @50183
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF(@50180) END
  WRITE_LONG 0x34 zst_price_spell_siphon_bg2ee

COPY_EXISTING ~zsipsps1.spl~ ~override~
              ~zsipsps3.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF(@50181) END

ACTION_IF GAME_IS "bgee eet" BEGIN

  COPY_EXISTING ~highhedg.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR flags=~identified~ item_name = "zsipsps0" position = "LAST" END

END

ACTION_IF GAME_IS "bg2ee eet" BEGIN

  COPY_EXISTING ~ribald.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR flags=~identified~ item_name = "ZSIPSPS2" position = "LAST" END

END

ACTION_IF GAME_IS "iwdee" BEGIN

  COPY_EXISTING ~highhedg.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR flags=~identified~ item_name = "zsipsps0" position = "LAST" END

END
