COPY ~%MOD_FOLDER%/items/01_forbidden_game/winkling_gloves~ ~override~
COPY_EXISTING ~zsipwkgv.itm~ ~override~
  SAY NAME2 @5120
  SAY IDENTIFIED_DESC @5121
  WRITE_LONG 0x34 zst_price_winkling_gloves_bg2ee

OUTER_SET is_eet = GAME_IS "eet"
OUTER_SET is_bg2ee = GAME_IS "bg2ee"

ACTION_IF is_bg2ee OR is_eet BEGIN

    COPY_EXISTING ~slshop02.sto~ ~override~
        LPF ADD_STORE_ITEM_EX STR_VAR item_name="zsipwkgv" position="LAST" flags=~identified~ END

END

ACTION_IF NOT is_bg2ee BEGIN

    COPY_EXISTING ~zsipwkgv.itm~ ~override/zsipwkgw.itm~
        WRITE_LONG 0x34 zst_price_winkling_gloves_bgee

END

ACTION_IF GAME_IS "bgee" OR is_eet BEGIN

    COPY_EXISTING ~nimbul.cre~ ~override~
        ADD_CRE_ITEM ~zsipwkgw~ #0 #0 #0 ~unstealable~ ~gloves inv~

END

ACTION_IF GAME_IS "iwdee" BEGIN

    COPY_EXISTING ~ar2115.are~ ~override~
        LPF ADD_AREA_ITEM INT_VAR container_to_add_to=2 STR_VAR item_to_add = ~zsipwkgw~ END

END