ACTION_IF (VARIABLE_IS_SET ~zs_itempack_311~) BEGIN
  FAIL ~Script already included: zs_itempack_311~
END ELSE BEGIN
  OUTER_SET ~zs_itempack_311~ = 1
END

COPY ~%MOD_FOLDER%/items/03_nwn/mercykiller_blade~ ~override~
COPY_EXISTING ~ZSIPMK0.itm~ ~override~
  SAY NAME2 @8024
  SAY IDENTIFIED_DESC @8025

COPY_EXISTING ~WMART2.STO~ ~override~
  LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR item_name = "ZSIPMK0" position = "LAST" flags= ~identified~ END

