COPY ~%MOD_FOLDER%/items/02_souls/crimson_life~ ~override~

ACTION_IF GAME_IS "iwdee" BEGIN
  OUTER_SPRINT desc @6102
END ELSE BEGIN
  OUTER_SPRINT desc @6101
END

COPY_EXISTING ~zsiplfc0.itm~ ~override~
  SAY NAME2 @6100
  WRITE_LONG IDENTIFIED_DESC desc
  WRITE_LONG 0x34 zst_price_crimson_life

ACTION_IF GAME_IS "bgee eet" BEGIN

  COPY_EXISTING ~tem2304.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR item_name = "zsiplfc0" position = "LAST" flags="identified" END

END

ACTION_IF GAME_IS "bg2ee eet" BEGIN

  COPY_EXISTING ~temlath.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR item_name = "zsiplfc0" position = "LAST" flags="identified" END

END

ACTION_IF GAME_IS "iwdee" BEGIN

  COPY_EXISTING ~kutemple.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR item_name = "zsiplfc0" position = "LAST" flags="identified" END

END
