COPY ~%MOD_FOLDER%/items/03_nwn/goblinsplitter~ ~override~
COPY_EXISTING ~zsipaxaa.itm~ ~override~
  SAY NAME2 @8019
  SAY IDENTIFIED_DESC @8020
  WRITE_LONG 0x34 zst_price_goblinsplitter

ACTION_IF GAME_IS ~bgee eet~ BEGIN

  COPY_EXISTING ~friend.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR item_name = "zsipaxaa" position = "LAST" END

END

ACTION_IF GAME_IS ~bg2ee eet~ BEGIN

  COPY_EXISTING ~ar0602.are~ ~override~
    LPF ADD_AREA_ITEM INT_VAR container_to_add_to = 38 STR_VAR item_to_add = ~zsipaxaa~ END

END

ACTION_IF GAME_IS ~iwdee~ BEGIN

  COPY_EXISTING ~towniem1.are~ ~override/zsipaxcr.cre~
    WRITE_SHORT 0x24 "-10" // dead
    REMOVE_CRE_ITEMS
    ADD_CRE_ITEM ~zsipaxaa~ #0 #0 #0 ~none~ ~inv~

  EXTEND_BOTTOM ~ar1000.bcs~ ~%MOD_FOLDER%/baf/area/goblinsplitter/ar1000.baf~

END
