COPY ~%MOD_FOLDER%/items/02_souls/sseth_revenge~ ~override~
ADD_PROJECTILE ~%MOD_FOLDER%/pro/sseth_revenge/ZSIPSSRZ.pro~

COPY_EXISTING ~zsipssr0.itm~ ~override~
  SAY NAME2 @18000
  SAY IDENTIFIED_DESC @18001
  WRITE_LONG 0x34 zst_price_sseth_revenge

COPY_EXISTING ~zsipssr2.itm~ ~override~
  SAY NAME2 @18002
  SAY IDENTIFIED_DESC @18003

COPY_EXISTING ~zsipssr6.spl~ ~override~
  LPF ALTER_HEADER INT_VAR projectile = %ZSIPSSRZ% END

COPY_EXISTING ~zsipyua1.cre~ ~override~
  SAY 0x08 @18004
  SAY 0x0c @18004

EXTEND_BOTTOM ~ar1513.bcs~ ~%MOD_FOLDER%/baf/area/sseth_revenge/ar1513.baf~
