COPY ~%MOD_FOLDER%/items/02_souls/ring_hardiness~ ~override~
COPY_EXISTING ~zsiprhr2.itm~ ~override~
  SAY NAME2 @6150
  SAY IDENTIFIED_DESC @6151
  LPF ALTER_EFFECT_EX INT_VAR parameter1=zst_ring_hardiness_dr STR_VAR match_opcode_ex="(o_opcode >= 86 AND o_opcode <= 89)" END

  PATCH_IF NOT GAME_IS "iwdee" BEGIN
    WRITE_LONG 0x34 zst_price_ring_hardiness_bg
  END ELSE BEGIN
    WRITE_LONG 0x34 zst_price_ring_hardiness_base_iwdee
  END

COPY_EXISTING ~zsiprhr3.itm~ ~override~
  SAY NAME2 @6152
  SAY IDENTIFIED_DESC @6153
  LPF ALTER_EFFECT_EX INT_VAR parameter1=zst_ring_hardiness_upgraded_dr STR_VAR match_opcode_ex="(o_opcode >= 86 AND o_opcode <= 89)" END
  WRITE_LONG 0x34 zst_price_ring_hardiness_bg_upgraded


ACTION_IF GAME_IS ~bgee eet~ BEGIN

  COPY_EXISTING ~kagain.cre~ ~override~
                ~kagain2.cre~ ~override~
                ~kagain4.cre~ ~override~
                ~kagain6.cre~ ~override~
    ADD_CRE_ITEM ~zsiprhr2.itm~ #0 #0 #0 ~none~ ~ring inv~

END

ACTION_IF GAME_IS ~bg2ee eet~ BEGIN

  COPY_EXISTING ~ar0602.are~ ~override~
    LPF ADD_AREA_ITEM INT_VAR container_to_add_to = 4 STR_VAR item_to_add = ~zsiprhr2~ END

  COMPILE ~%MOD_FOLDER%/dlg/upgrades/zs_itempack_ring_hardiness_crommy.d~
  EXTEND_BOTTOM ~ar0334.bcs~ ~%MOD_FOLDER%/baf/upgrades/ring_hardiness/ar0334.baf~

END

ACTION_IF GAME_IS ~iwdee~ BEGIN

  COPY_EXISTING ~kusmith.sto~ ~override~
      LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR flags=~identified~ item_name = "zsiprhr2" position = "LAST" END

END
