COPY "%MOD_FOLDER%/items/03_nwn/lawgiver" ~override~
COPY_EXISTING ~zsiplg0.itm~ ~override~
  SAY NAME2 @8000
  SAY IDENTIFIED_DESC @8001
  WRITE_LONG 0x34 zst_price_lawgiver

ACTION_IF GAME_IS "bgee eet" BEGIN

  COPY_EXISTING ~flam2.cre~ ~override~
    ADD_CRE_ITEM ~zsiplg0~ #0 #0 #0 ~unstealable~ ~weapon1~ EQUIP

END

ACTION_IF GAME_IS "bg2ee eet" BEGIN

  COPY_EXISTING ~bhelm.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR flags=~identified~ item_name = "zsiplg0" position = "LAST" END

END

ACTION_IF GAME_IS "iwdee" BEGIN

  COPY_EXISTING ~kutemple.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR flags=~identified~ item_name = "zsiplg0" position = "LAST" END

END
