COPY ~%MOD_FOLDER%/items/01_bg3/hood_weave~ ~override~
COPY_EXISTING ~zsiphdwv.itm~ ~override~
  SAY NAME2 @5160
  SAY IDENTIFIED_DESC @5161
  WRITE_LONG 0x34 zst_price_cowl_weave

ACTION_IF GAME_IS "bg2ee" OR is_eet BEGIN

    COPY_EXISTING ~bmthief.sto~ ~override~
        LPF ADD_STORE_ITEM_EX STR_VAR item_name="zsiphdwv" position="LAST" flags=~identified~ END

END

ACTION_IF GAME_IS "bgee" OR GAME_IS "eet" BEGIN

    ACTION_IF GAME_INCLUDES "sod" BEGIN

        COPY_EXISTING ~bdsorcs.sto~ ~override~
            LPF ADD_STORE_ITEM_EX STR_VAR item_name="zsiphdwv" position="LAST" flags=~identified~ END

    END ELSE BEGIN

        COPY_EXISTING ~sto0703.sto~ ~override~
            LPF ADD_STORE_ITEM_EX STR_VAR item_name="zsiphdwv" position="LAST" flags=~identified~ END

    END

END

ACTION_IF GAME_IS "iwdee" BEGIN

    COPY_EXISTING ~malavon.cre~ ~override~
        ADD_CRE_ITEM ~zsiphdwv~ #0 #0 #0 ~none~ ~helmet inv~

END