COPY ~%MOD_FOLDER%/items/01_forbidden_game/bloodthirst~ ~override~
ACTION_IF GAME_IS ~bgee eet~ BEGIN

    COPY_EXISTING ~zsipblt0.itm~ ~override~
        SAY NAME2 @5004
        SAY IDENTIFIED_DESC @5005
        WRITE_LONG 0x34 zst_price_bloodthirst_bgee

    COPY_EXISTING ~zsipblt1.spl~ ~override~
                  ~zsipblt2.spl~ ~override~
        LPF ALTER_EFFECT INT_VAR match_opcode = 318 parameter2 = zs_piercing_immunity END

    COPY_EXISTING ~winski2.cre~ ~override~
        ADD_CRE_ITEM ~zsipblt0~ #0 #0 #0 ~none~ ~inv~

END

ACTION_IF GAME_IS ~bg2ee eet~ BEGIN

    COPY_EXISTING ~zsipblt3.itm~ ~override~
        SAY NAME2 @50060
        SAY IDENTIFIED_DESC @50061
        WRITE_LONG 0x34 zst_price_bloodthirst_bg2ee

    COPY_EXISTING ~zsipblt6.itm~ ~override~
        SAY NAME2 @50062
        SAY IDENTIFIED_DESC @50063
        WRITE_LONG 0x34 zst_price_bloodthirst_bg2ee_upgraded

    COPY_EXISTING ~zsipblt4.spl~ ~override~
                  ~zsipblt5.spl~ ~override~
                  ~zsipblt7.spl~ ~override~
                  ~zsipblt8.spl~ ~override~
        LPF ALTER_EFFECT INT_VAR match_opcode = 318 parameter2 = zs_piercing_immunity END

    COPY_EXISTING ~c6bodhi.cre~ ~override~
        ADD_CRE_ITEM ~zsipblt3~ #0 #0 #0 ~unstealable~ ~inv~

    COMPILE ~%MOD_FOLDER%/dlg/upgrades/zs_itempack_bloodthirst_cespy.d~
    EXTEND_BOTTOM ~botsmith.bcs~ ~%MOD_FOLDER%/baf/upgrades/bloodthirst/botsmith.baf~

END
