COPY ~%MOD_FOLDER%/items/02_souls/moonlit_slumber~ ~override~
ADD_PROJECTILE ~%MOD_FOLDER%/pro/mists_slumber/zsipmscd.pro~
COPY_EXISTING ~zsiptrna.itm~ ~override~
  SAY NAME2 @6011
  SAY IDENTIFIED_DESC @6010
  WRITE_LONG 0x34 zst_price_moonlit_slumber

COPY_EXISTING ~zsiptrms.spl~ ~override~
  SAY NAME1 @6012
  LPF ALTER_HEADER INT_VAR projectile = %zsipmscd% END

ACTION_IF GAME_IS "bgee eet" BEGIN

  COPY_EXISTING ~sto0703.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR item_name = "zsiptrna" position = "LAST" END

END

ACTION_IF GAME_IS "bg2ee eet" BEGIN

  COPY_EXISTING ~ribald.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR item_name = "zsiptrna" position = "LAST" flags="identified" END

END

ACTION_IF GAME_IS "bg2ee eet" BEGIN

  COPY_EXISTING ~shlehlan.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR item_name = "zsiptrna" position = "LAST" flags="identified" END

END
