ACTION_IF (VARIABLE_IS_SET ~zs_itempack_216~) BEGIN
  FAIL ~Script already included: zs_itempack_216~
END ELSE BEGIN
  OUTER_SET ~zs_itempack_216~ = 1
END

COPY ~%MOD_FOLDER%/items/02_souls/icicle~ ~override~
COPY_EXISTING ~ZSIPICI0.itm~ ~override~
    SAY NAME2 @6070
    SAY IDENTIFIED_DESC @6071
BUT_ONLY

COPY_EXISTING ~UDMASTER.CRE~ ~override~
    ADD_CRE_ITEM ~ZSIPICI0.itm~ #1 #0 #0 ~unstealable~ ~inv~
