COPY ~%MOD_FOLDER%/items/05_tv/needle~ ~override~
COPY_EXISTING ~zsipndl0.itm~ ~override~
  SAY NAME1 @80110
  SAY NAME2 @12000
  SAY UNIDENTIFIED_DESC @80111
  SAY IDENTIFIED_DESC @12001
  WRITE_LONG 0x34 zst_price_needle

ACTION_IF GAME_IS ~bgee eet~ BEGIN

  COPY_EXISTING ~tem4003.sto~ ~override~
    LPF ADD_STORE_ITEM_EX INT_VAR charge1 = 1 STR_VAR item_name = "zsipndl0" position = "LAST" flags = ~identified~ END

END

ACTION_IF GAME_IS ~bg2ee eet~ BEGIN

  COPY_EXISTING ~obshal01.cre~ ~override~
    ADD_CRE_ITEM ~zsipndl0~ #0 #0 #0 ~none~ ~inv~

END

INCLUDE ~%MOD_FOLDER%/libs/zs_add_rapiers.tph~
