COPY ~%MOD_FOLDER%/items/04_me/rod_illusive~ ~override~
COPY_EXISTING ~zsipril0.itm~ ~override~
  SAY NAME2 @10110
  SAY IDENTIFIED_DESC @10111
  WRITE_LONG 0x34 zst_price_rod_illusive

ACTION_IF GAME_IS "bgee eet" BEGIN

  ACTION_IF GAME_INCLUDES "sod" BEGIN

    COPY_EXISTING ~bdsorcsc.sto~ ~override~ // sorcerous sundries (SoD)
      LPF ADD_STORE_ITEM_EX INT_VAR charge1=1 STR_VAR item_name="zsipril0" position="LAST" flags=~identified~ END

  END ELSE BEGIN

    COPY_EXISTING ~sto0703.sto~  ~override~ // sorcerous sundries
      LPF ADD_STORE_ITEM_EX INT_VAR charge1=1 STR_VAR item_name="zsipril0" position="LAST" flags=~identified~ END

  END

END 

ACTION_IF GAME_IS "bg2ee eet" BEGIN

  COPY_EXISTING ~wmart2.sto~  ~override~ // deidre
    LPF ADD_STORE_ITEM_EX INT_VAR charge1=1 STR_VAR item_name="zsipril0" position="LAST" flags=~identified~ END

END
