ACTION_IF zst_generic_variants AND zst_generic_variants_shurikens AND NOT FILE_EXISTS_IN_GAME ~zsipshup.itm~ BEGIN

    COPY ~%MOD_FOLDER%/items/generic/shuriken~ ~override~
    COPY_EXISTING ~zsipshu0.itm~ ~override~
                  ~zsipshu1.itm~ ~override~
                  ~zsipshu2.itm~ ~override~
                  ~zsipshu3.itm~ ~override~
                  ~zsipshu4.itm~ ~override~
                  ~zsipshu5.itm~ ~override~
                  ~zsipshup.itm~ ~override~
                  ~zsipshub.itm~ ~override~
                  ~zsipshua.itm~ ~override~
        SAY NAME1 @15070
        SAY NAME2 @15070
        SAY UNIDENTIFIED_DESC @15071
        SAY IDENTIFIED_DESC @15071

    COPY_EXISTING ~zsipshu0.itm~ ~override~
        SAY NAME2 @15070
        SAY IDENTIFIED_DESC @15071

    COPY_EXISTING ~zsipshu1.itm~ ~override~
        SAY NAME2 @15072
        SAY IDENTIFIED_DESC @15073

    COPY_EXISTING ~zsipshu2.itm~ ~override~
        SAY NAME2 @15074
        SAY IDENTIFIED_DESC @15075

    COPY_EXISTING ~zsipshu3.itm~ ~override~
        SAY NAME2 @15076
        SAY IDENTIFIED_DESC @15077

    COPY_EXISTING ~zsipshu4.itm~ ~override~
        SAY NAME2 @15078
        SAY IDENTIFIED_DESC @15079

    COPY_EXISTING ~zsipshu5.itm~ ~override~
        SAY NAME2 @15080
        SAY IDENTIFIED_DESC @15081

    COPY_EXISTING ~zsipshup.itm~ ~override~
        SAY NAME2 @15082
        SAY IDENTIFIED_DESC @15083

    COPY_EXISTING ~zsipshub.itm~ ~override~
        SAY NAME2 @15084
        SAY IDENTIFIED_DESC @15085
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF(@15086) END
        LPF ALTER_EFFECT INT_VAR match_opcode=318 match_parameter1=0 match_parameter2=0 parameter2=zs_has_stoneskins END

    COPY_EXISTING ~zsipshua.itm~ ~override~
        SAY NAME2 @15087
        SAY IDENTIFIED_DESC @15088

    ACTION_IF GAME_IS ~bgee eet~ BEGIN
        // +0

        COPY_EXISTING ~bdbelega.sto~ ~override~ // Belegarm's store (quartermaster SoD)
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=80 unlimited=1 STR_VAR item_name="zsipshu0" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~erdane.sto~  ~override~ // erdane (durlag's tower)
                      ~friend.sto~  ~override~ // friendly arm inn
                      ~sto4803.sto~  ~override~ // nashkel store
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=10 stack=5 STR_VAR item_name="zsipshu0" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~inn2616.sto~ ~override~ // winthrop
                      ~inn3304.sto~  ~override~ // jovial jugler
                      ~sto1116.sto~  ~override~ // general store
                      ~sto1302.sto~  ~override~ // general store
                      ~sto4909.sto~  ~override~ // carnival shop
                      ~tav0810.sto~  ~override~ // maltz's weapon shop
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=10 unlimited=1 STR_VAR item_name="zsipshu0" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~erdane.sto~  ~override~ // erdane (durlag's tower)
                      ~friend.sto~  ~override~ // friendly arm inn
                      ~ulgoth.sto~   ~override~ // ulgoth's beard store
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=10 stack=5 STR_VAR item_name="zsipshu0" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~taerum.sto~   ~override~ // thunderhammer's smithy
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=20 stack=100 STR_VAR item_name="zsipshu0" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        // +1
        COPY_EXISTING ~bdbelega.sto~ ~override~ // Belegarm's store (quartermaster SoD)
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=80 unlimited=1 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~bdsorcsc.sto~ ~override~ // sorcerous sundries (sod)
                      ~sto0703.sto~  ~override~ // sorcerous sundries
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=5 stack = 100 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~erdane.sto~ ~override~ // erdane
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=10 stack = 50 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~highhedg.sto~ ~override~ // high hedge
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=5 stack = 300 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~stoblack.sto~ ~override~ // black lily
                      ~stosilen.sto~ ~override~ // silence
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=5 stack = 50 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~taerum.sto~ ~override~ // thunderhammer's smithy
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=10 stack=200 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~ulgoth.sto~ ~override~ // thunderhammer's smithy
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=10 stack=10 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        // +2 / poison / bleed / acid

        COPY_EXISTING ~bdwaizah.sto~ ~override~ // thieves guild sof
            // LPF ADD_STORE_ITEM_EX INT_VAR charge1=80 stack=10 STR_VAR item_name="ZSIPSHU2" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=80 stack=8 STR_VAR item_name="zsipshup" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=40 stack=5 STR_VAR item_name="zsipshub" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=60 stack=5 STR_VAR item_name="zsipshua" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~bdsorcsc.sto~ ~override~ // sorcerous sundries (SoD)
                      ~STO0703.sto~  ~override~ // sorcerous sundries
            // LPF ADD_STORE_ITEM_EX INT_VAR charge1=5 stack=100 STR_VAR item_name="ZSIPSHU2" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=5 stack=100 STR_VAR item_name="zsipshup" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=5 stack=100 STR_VAR item_name="zsipshub" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=5 stack=100 STR_VAR item_name="zsipshua" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~stoblack.STO~ ~override~ // black lily
                      ~stosilen.STO~ ~override~ // silence
            // LPF ADD_STORE_ITEM_EX INT_VAR charge1=5 stack=30 STR_VAR item_name="ZSIPSHU2" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=5 stack=30 STR_VAR item_name="zsipshup" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=5 stack=30 STR_VAR item_name="zsipshub" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=5 stack=30 STR_VAR item_name="zsipshua" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

    END

    ACTION_IF GAME_IS ~bg2ee eet~ BEGIN
        // +0
        COPY_EXISTING ~amsmug01.sto~    ~override~ // smugglers 1
                      ~amsmug02.sto~    ~override~ // smugglers 2
                      ~arled.sto~       ~override~ // arled
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=20 stack=10 STR_VAR item_name="zsipshu0" position="LAST" flags=~identified~ END

        COPY_EXISTING ~bernard.sto~   ~override~ // bernard 1
                      ~bernard2.sto~  ~override~ // bernard 2
                      ~bernard3.sto~  ~override~ // bernard 3
                      ~bernard4.sto~  ~override~ // bernard 4
                      ~bmthief.sto~   ~override~ // shadow thief fence
                      ~gorch.sto~     ~override~ // gorch
                      ~hendak.sto~    ~override~ // hendak
                      ~lehtinan.sto~  ~override~ // lehtinan
                      ~ribald.sto~    ~override~ // ribald
                      ~ribald2.sto~   ~override~ // ribald
                      ~shthstor.sto~  ~override~ // ratell
                      ~trmer03.sto~  ~override~ // fletcher
                      ~sarbar01.sto~  ~override~ // saradush inn
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=20 unlimited=1 STR_VAR item_name="zsipshu0" position="LAST" flags=~identified~ END

        // +1
        COPY_EXISTING ~amsmug01.sto~  ~override~ // smugglers 1
                      ~amsmug02.sto~  ~override~ // smugglers 2
                      ~arled.sto~     ~override~ // arled
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=10 stack=10 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END

        COPY_EXISTING ~bernard3.sto~  ~override~ // bernard 3
                      ~bernard4.sto~  ~override~ // bernard 4
                      ~gorch.sto~     ~override~ // gorch
                      ~bmthief.sto~   ~override~ // shadow thief fence
                      ~hendak.sto~    ~override~ // hendak
                      ~ribald.sto~    ~override~ // ribald
                      ~ribald2.sto~   ~override~ // ribald
                      ~udduer02.sto~  ~override~ // duergar merchant
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=20 stack=5 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END

        COPY_EXISTING ~garlena.sto~  ~override~ // garlena helm
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=10 stack=4 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END

        COPY_EXISTING ~hgkar01.sto~  ~override~ // hgkar
                      ~sarbar01.sto~  ~override~ // saradush inn
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=40 stack=40 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END

        COPY_EXISTING ~sahpr1.sto~  ~override~ // sekolah temple
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=10 stack=4 STR_VAR item_name="zsipshu1" position="LAST" flags=~identified~ END

        // +2
        COPY_EXISTING ~bernard5.sto~ ~override~ // bernard 5
                      ~bernard6.sto~ ~override~ // bernard 6
                      ~hendak.sto~   ~override~ // merchant
                      ~ohngduke.sto~ ~override~ // gul dukeem
                      ~ribald3.sto~  ~override~ // ribald
            // LPF ADD_STORE_ITEM_EX INT_VAR charge1=40 stack=10 STR_VAR item_name="ZSIPSHU2" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=30 stack=8 STR_VAR item_name="zsipshua" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=20 stack=6 STR_VAR item_name="zsipshup" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=20 stack=6 STR_VAR item_name="zsipshub" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~arled.sto~ ~override~ // ARLED
            // LPF ADD_STORE_ITEM_EX INT_VAR charge1=40 stack=4 STR_VAR item_name="ZSIPSHU2" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=30 stack=3 STR_VAR item_name="zsipshua" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=20 stack=2 STR_VAR item_name="zsipshup" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=20 stack=2 STR_VAR item_name="zsipshub" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~hgkar01.sto~   ~override~ // karthis
                      ~sarbar01.sto~  ~override~ // saradush bar
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=40 stack=40 STR_VAR item_name="zsipshu2" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

         // +3
        COPY_EXISTING ~amsmug01.sto~  ~override~ // amekthran smugglers1
                      ~amsmug02.sto~  ~override~ // amekthran smugglers1
                      ~hgkar01.sto~   ~override~ // karthis
                      ~sarbar01.sto~  ~override~ // saradush bar
                      ~ohnsdwm.sto~   ~override~ // merchant
            // LPF ADD_STORE_ITEM_EX INT_VAR charge1=40 stack=40 STR_VAR item_name="ZSIPSHU3" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=40 stack=30 STR_VAR item_name="zsipshua" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=40 stack=20 STR_VAR item_name="zsipshup" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=40 stack=20 STR_VAR item_name="zsipshub" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        // +4 / +5
        COPY_EXISTING ~amsmug01.sto~  ~override~ // amekthran smugglers1
                      ~amsmug02.sto~  ~override~ // amekthran smugglers1
                      ~hgkar01.sto~   ~override~ // karthis
                      ~sarbar01.sto~  ~override~ // saradush bar
                      ~ohnsdwm.sto~   ~override~ // merchant
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=40 stack=30 STR_VAR item_name="zsipshu4" position="LAST" flags=~identified~ END
            LPF ADD_STORE_ITEM_EX INT_VAR charge1=40 stack=20 STR_VAR item_name="zsipshu5" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

    END
END
