ACTION_IF zst_generic_variants AND zst_generic_variants_kukris AND NOT FILE_EXISTS_IN_GAME ~zsipkuk0.itm~ BEGIN

    COPY ~%MOD_FOLDER%/items/generic/kukri~ ~override~
    COPY_EXISTING ~zsipkuk0.itm~ ~override~
                  ~zsipkuk1.itm~ ~override~
                  ~zsipkuk2.itm~ ~override~
                  ~zsipkuk3.itm~ ~override~
        SAY NAME1 @80060
        SAY NAME2 @80060
        SAY UNIDENTIFIED_DESC @80061
        SAY IDENTIFIED_DESC @80061

    COPY_EXISTING ~zsipkuk1.itm~ ~override~
        SAY NAME2 @80062
        SAY IDENTIFIED_DESC @80063

    COPY_EXISTING ~zsipkuk2.itm~ ~override~
        SAY NAME2 @80064
        SAY IDENTIFIED_DESC @80065

    COPY_EXISTING ~zsipkuk3.itm~ ~override~
        SAY NAME2 @80066
        SAY IDENTIFIED_DESC @80067

    ACTION_IF GAME_IS ~bgee eet~ BEGIN
        // +0
        COPY_EXISTING ~inn2616.sto~  ~override~ // winthrop
                      ~inn3304.sto~  ~override~ // jovial jugler
                      ~sto1112.sto~  ~override~ // general store
                      ~sto1320.sto~  ~override~ // general store
                      ~sto4803.sto~  ~override~ // nashkel store
                      ~sto4908.sto~  ~override~ // carnival shop
                      ~stoblack.sto~ ~override~ // black lily
                      ~stosilen.sto~ ~override~ // shop of silence
                      ~taerum.sto~   ~override~ // thunderhammer's smithy
                      ~tav0810.sto~  ~override~ // maltz's weapon shop
                      ~ulgoth.sto~   ~override~ // ulgoth's beard store
                      ~friend.sto~   ~override~ // friendly arm inn
                      ~bdbelega.sto~ ~override~ // belegarm's store (quartermaster sod)
            SET amount = RANDOM(2 7)
            LPF ADD_STORE_ITEM_EX INT_VAR stack=amount STR_VAR item_name="zsipkuk0" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        // +1
        COPY_EXISTING ~inn3351.sto~  ~override~ // feldepost inn
                      ~sto0703.sto~  ~override~ // sorcerous sundries
                      ~sto1117.sto~  ~override~ // general store
                      ~sto4907.sto~  ~override~ // carnival shop
                      ~taerum.sto~   ~override~ // thunderhammer's smithy
                      ~bdbelega.sto~ ~override~ // belegarm's store (quartermaster sod)
            SET amount = RANDOM(1 2)
            LPF ADD_STORE_ITEM_EX INT_VAR stack=amount STR_VAR item_name="zsipkuk1" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        // +2
        COPY_EXISTING ~sto0703.sto~  ~override~ // sorcerous sundries
                      ~bdbelega.sto~ ~override~ // belegarm's store (quartermaster sod)
            LPF ADD_STORE_ITEM_EX INT_VAR stack=1 STR_VAR item_name="zsipkuk2" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

    END

    ACTION_IF GAME_IS ~bg2ee eet~ BEGIN
        COPY_EXISTING ~shop01.sto~   ~override~ // mira
                      ~shop03.sto~   ~override~ // maheed
                      ~shop04.sto~   ~override~ // store owner that talks in a way that is difficult to understand
                      ~shop06.sto~   ~override~ // hes
                      ~shop07.sto~   ~override~ // another store in waukeen promenade
                      ~shthstor.sto~ ~override~ // ratell
                      ~arled.sto~    ~override~ // arled
                      ~bernard.sto~  ~override~ // bernard 1
                      ~bernard2.sto~ ~override~ // bernard 2
                      ~bernard3.sto~ ~override~ // bernard 3
                      ~bernard4.sto~ ~override~ // bernard 4
                      ~bernard5.sto~ ~override~ // bernard 5
                      ~bernard6.sto~ ~override~ // bernard 6
                      ~bmthief.sto~  ~override~ // shadow thief fence
                      ~ambar01.sto~  ~override~ // the zephyr
                      ~amsmug01.sto~ ~override~ // amekthran smugglers1
                      ~amsmug02.sto~ ~override~ // amekthran smugglers1
                      ~gorch.sto~    ~override~ // gorch
                      ~hendak.sto~   ~override~ // hendak
                      ~lehtinan.sto~ ~override~ // lehtinan
                      ~uddrow22.sto~ ~override~ // drow merchant
                      ~uddrow23.sto~ ~override~ // drow merchant
            SET amount = RANDOM(1 5)
            LPF ADD_STORE_ITEM_EX INT_VAR stack=amount STR_VAR item_name="zsipkuk0" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        COPY_EXISTING ~arled.sto~    ~override~ // arled
                      ~bernard.sto~  ~override~ // bernard 1
                      ~bernard2.sto~ ~override~ // bernard 2
                      ~bernard3.sto~ ~override~ // bernard 3
                      ~bernard4.sto~ ~override~ // bernard 4
                      ~bernard5.sto~ ~override~ // bernard 5
                      ~bernard6.sto~ ~override~ // bernard 6
                      ~bmthief.sto~  ~override~ // shadow thief fence
                      ~ambar01.sto~  ~override~ // the zephyr
                      ~amsmug01.sto~ ~override~ // amekthran smugglers1
                      ~amsmug02.sto~ ~override~ // amekthran smugglers1
                      ~gorch.sto~    ~override~ // gorch
                      ~hendak.sto~   ~override~ // hendak
                      ~lehtinan.sto~ ~override~ // lehtinan
                      ~uddrow22.sto~ ~override~ // drow merchant
                      ~uddrow23.sto~ ~override~ // drow merchant
                      ~ribald.sto~   ~override~ // ribald
                      ~ribald2.sto~  ~override~ // ribald
            LPF ADD_STORE_ITEM_EX INT_VAR stack=1 STR_VAR item_name="zsipkuk1" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

         // +2
        COPY_EXISTING ~bernard5.sto~ ~override~ // bernard 5
                      ~bernard6.sto~ ~override~ // bernard 6
                      ~ohnsdwm.sto~  ~override~ // merchant
                      ~trmer04a.sto~ ~override~ // anvir of the right
                      ~ribald.sto~   ~override~ // ribald
                      ~ribald3.sto~  ~override~ // ribald
                      ~hgkar01.sto~  ~override~ // karthis
                      ~sarbar01.sto~ ~override~ // saradush bar
            LPF ADD_STORE_ITEM_EX INT_VAR stack=1 STR_VAR item_name="zsipkuk2" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

         // +3
        COPY_EXISTING ~amsmug01.sto~ ~override~ // amekthran smugglers1
                      ~amsmug02.sto~ ~override~ // amekthran smugglers1
                      ~hgkar01.sto~  ~override~ // karthis
                      ~sarbar01.sto~ ~override~ // saradush bar
                      ~ohnsdwm.sto~  ~override~ // merchant
            LPF ADD_STORE_ITEM_EX INT_VAR stack=1 STR_VAR item_name="zsipkuk3" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

    END
END
