ACTION_IF zst_generic_variants AND zst_generic_variants_rapiers AND NOT FILE_EXISTS_IN_GAME ~zsiprap0.itm~ BEGIN

    COPY ~%MOD_FOLDER%/items/generic/rapier~ ~override~
    COPY_EXISTING ~zsiprap0.itm~ ~override~
                  ~zsiprap1.itm~ ~override~
                  ~zsiprap2.itm~ ~override~
                  ~zsiprap3.itm~ ~override~
        SAY NAME1 @80110
        SAY NAME2 @80110
        SAY UNIDENTIFIED_DESC @80111
        SAY IDENTIFIED_DESC @80111

    COPY_EXISTING ~zsiprap1.itm~ ~override~
        SAY NAME2 @80112
        SAY IDENTIFIED_DESC @80113

    COPY_EXISTING ~zsiprap2.itm~ ~override~
        SAY NAME2 @80114
        SAY IDENTIFIED_DESC @80115

    COPY_EXISTING ~zsiprap3.itm~ ~override~
        SAY NAME2 @80116
        SAY IDENTIFIED_DESC @80117

    ACTION_IF GAME_IS ~bgee eet~ BEGIN
        // +0
        COPY_EXISTING ~inn2616.sto~  ~override~ // winthrop
                      ~inn3304.sto~  ~override~ // jovial jugler
                      ~sto1112.sto~  ~override~ // general store
                      ~sto1320.sto~  ~override~ // general store
                      ~sto4803.sto~  ~override~ // nashkel store
                      ~sto4908.sto~  ~override~ // carnival shop
                      ~stoblack.sto~ ~override~ // black lily
                      ~stosilen.sto~ ~override~ // shop of silence
                      ~taerum.sto~   ~override~ // thunderhammer's smithy
                      ~tav0810.sto~  ~override~ // maltz's weapon shop
                      ~ulgoth.sto~   ~override~ // ulgoth's beard store
                      ~friend.sto~   ~override~ // friendly arm inn
                      ~bdbelega.sto~ ~override~ // belegarm's store (quartermaster sod)
            SET amount = RANDOM(1 5)
            LPF ADD_STORE_ITEM_EX INT_VAR stack=amount STR_VAR item_name="zsiprap0" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        // +1
        COPY_EXISTING ~inn3351.sto~  ~override~ // feldepost inn
                      ~sto0703.sto~  ~override~ // sorcerous sundries
                      ~sto1117.sto~  ~override~ // general store
                      ~sto4907.sto~  ~override~ // carnival shop
                      ~taerum.sto~   ~override~ // thunderhammer's smithy
                      ~bdbelega.sto~ ~override~ // belegarm's store (quartermaster sod)
            LPF ADD_STORE_ITEM_EX INT_VAR stack=1 STR_VAR item_name="zsiprap1" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        ACTION_IF zst_give_skie_bgee_rapier1 BEGIN
            // skie uses a rapier now, since it's a noble weapon
            COPY_EXISTING ~skie.cre~  ~override~
                          ~skie6.cre~ ~override~
                ADD_CRE_ITEM ~zsiprap1~ #0 #0 #0 ~none~ ~weapon2~ EQUIP // CHECK COMPATIBILITY WITH LAVA'S MOD
        END

        // +2
        COPY_EXISTING ~sto0703.sto~  ~override~ // sorcerous sundries
                      ~bdbelega.sto~ ~override~ // belegarm's store (quartermaster sod)
            LPF ADD_STORE_ITEM_EX INT_VAR stack=1 STR_VAR item_name="zsiprap2" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS
    END

    ACTION_IF GAME_IS ~bg2ee eet~ BEGIN
        // +0
        COPY_EXISTING ~shop01.sto~   ~override~ // mira
                      ~shop03.sto~   ~override~ // maheed
                      ~shop04.sto~   ~override~ // store owner that talks in a way that is difficult to understand
                      ~shop06.sto~   ~override~ // hes
                      ~shop07.sto~   ~override~ // another store in waukeen promenade
                      ~shthstor.sto~ ~override~ // ratell
                      ~arled.sto~    ~override~ // arled
                      ~bernard.sto~  ~override~ // bernard 1
                      ~bernard2.sto~ ~override~ // bernard 2
                      ~bernard3.sto~ ~override~ // bernard 3
                      ~bernard4.sto~ ~override~ // bernard 4
                      ~bernard5.sto~ ~override~ // bernard 5
                      ~bernard6.sto~ ~override~ // bernard 6
                      ~bmthief.sto~  ~override~ // shadow thief fence
                      ~ambar01.sto~  ~override~ // the zephyr
                      ~amsmug01.sto~ ~override~ // amekthran smugglers1
                      ~amsmug02.sto~ ~override~ // amekthran smugglers1
                      ~gorch.sto~    ~override~ // gorch
                      ~hendak.sto~   ~override~ // hendak
                      ~lehtinan.sto~ ~override~ // lehtinan
                      ~uddrow22.sto~ ~override~ // drow merchant
                      ~uddrow23.sto~ ~override~ // drow merchant
            SET amount = RANDOM(1 5)
            LPF ADD_STORE_ITEM_EX INT_VAR stack=amount STR_VAR item_name="zsiprap0" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        ACTION_IF zst_give_nalia_soa_rapier0 BEGIN
        // nalia uses a rapier now, since it's a noble weapon
            COPY_EXISTING ~nalia8.cre~ ~override~
                LPF IS_WEAPON_EQUIPPED INT_VAR at_slot=1 STR_VAR weapon=~sw1h07~ RET found END
                PATCH_IF found BEGIN
                    ADD_CRE_ITEM ~zsiprap0~ #0 #0 #0 ~none~ ~weapon1~ EQUIP
                END
        END

        // +1
        COPY_EXISTING ~arled.sto~    ~override~ // arled
                      ~bernard.sto~  ~override~ // bernard 1
                      ~bernard2.sto~ ~override~ // bernard 2
                      ~bernard3.sto~ ~override~ // bernard 3
                      ~bernard4.sto~ ~override~ // bernard 4
                      ~bernard5.sto~ ~override~ // bernard 5
                      ~bernard6.sto~ ~override~ // bernard 6
                      ~bmthief.sto~  ~override~ // shadow thief fence
                      ~ambar01.sto~  ~override~ // the zephyr
                      ~amsmug01.sto~ ~override~ // amekthran smugglers1
                      ~amsmug02.sto~ ~override~ // amekthran smugglers1
                      ~gorch.sto~    ~override~ // gorch
                      ~hendak.sto~   ~override~ // hendak
                      ~lehtinan.sto~ ~override~ // lehtinan
                      ~uddrow22.sto~ ~override~ // drow merchant
                      ~uddrow23.sto~ ~override~ // drow merchant
                      ~ribald.sto~   ~override~ // ribald
                      ~ribald2.sto~  ~override~ // ribald
            LPF ADD_STORE_ITEM_EX INT_VAR stack=1 STR_VAR item_name="zsiprap1" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

        // +2
        COPY_EXISTING ~bernard5.sto~ ~override~ // bernard 5
                      ~bernard6.sto~ ~override~ // bernard 6
                      ~ohnsdwm.sto~  ~override~ // merchant
                      ~trmer04a.sto~ ~override~ // anvir of the right
                      ~ribald.sto~   ~override~ // ribald
                      ~ribald3.sto~  ~override~ // ribald
                      ~hgkar01.sto~  ~override~ // karthis
                      ~sarbar01.sto~ ~override~ // saradush bar
            LPF ADD_STORE_ITEM_EX INT_VAR stack=1 STR_VAR item_name="zsiprap2" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

         // +3
        COPY_EXISTING ~amsmug01.sto~ ~override~ // amekthran smugglers1
                      ~amsmug02.sto~ ~override~ // amekthran smugglers1
                      ~hgkar01.sto~  ~override~ // karthis
                      ~sarbar01.sto~ ~override~ // saradush bar
                      ~ohnsdwm.sto~  ~override~ // merchant
            LPF ADD_STORE_ITEM_EX INT_VAR stack=1 STR_VAR item_name="zsiprap3" position="LAST" flags=~identified~ END
        BUT_ONLY IF_EXISTS

    END
END
